-- Table: public.emailremetente
-- DROP TABLE IF EXISTS public."emailremetente";
CREATE TABLE IF NOT EXISTS public.emailremetente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username character varying(250) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(50) COLLATE pg_catalog."default" NOT NULL,
    host character varying(255) COLLATE pg_catalog."default" NOT NULL,
    port integer,
    CONSTRAINT emailremetente_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.emailremetente
    OWNER to postgres;